ASEEMDEV/force-app/main/default/objects/Lead/fields/Convert_to_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Convert_to_Opportunity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Convert to Opportunity</label>
    <type>Checkbox</type>
</CustomField>

ASEEMDEV/force-app/main/default/objects/Lead/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASEEMDEV/force-app/main/default/objects/Lead/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <referenceTo>Sales_Representative__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

ASEEMDEV/force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <label>Sales Representative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ASEEMDEV/force-app/main/default/objects/Sales_Representative__c/fields/Active_Leads__c.field-meta.xml
<CustomField>
    <fullName>Active_Leads__c</fullName>
    <label>Active Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ASEEMDEV/force-app/main/default/objects/Sales_Representative__c/fields/Industry_Specialization__c.field-meta.xml
<CustomField>
    <fullName>Industry_Specialization__c</fullName>
    <label>Industry Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASEEMDEV/force-app/main/default/objects/Sales_Representative__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASEEMDEV/force-app/main/default/objects/Sales_Representative__c/fields/Source_Specialization__c.field-meta.xml
<CustomField>
    <fullName>Source_Specialization__c</fullName>
    <label>Source Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Partner Referral</fullName>
            </value>
            <value>
                <fullName>Phone Inquiry</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Word of mouth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASEEMDEV/force-app/main/default/classes/LeadTriggerHelper.cls
/*******************************************************************************************************
* 
* @ Name            :   LeadTriggerHelper
* @ Purpose         :   Helper class for LeadTrigger.apxt
* @ Methods         :   1) assignSalesRep - To assign sales rep based on certain conditions
* @ Methods         :   2) validateLeadToOpportunityCreation - validate lead before it gets converted to an Opportunity
* @ Author          :   Aseem Doddamani
* @ Usage           :   
* @ Test Class Name :   TriggerHelperTest
*
*   Date            |  Developer Name                 |  Version      |  Changes
* ======================================================================================================
*   21-04-2024      |  aseem.doddamani@gmail.com      |  1.0          |  Initial Version
*
*******************************************************************************************************/
public class LeadTriggerHelper {
    
    public static void assignSalesRep(List<Lead> list_newLeads) {
        
        try{
            //Retrieve all Sales Rep with the least workload task
            Map<String,Sales_Representative__c> map_keyValuesBySalesRep = new Map<String,Sales_Representative__c>();
            List<Sales_Representative__c> list_SalesRep = [SELECT ID,Location__c,Source_Specialization__c,Industry_Specialization__c,Active_Leads__c
                                                           FROM Sales_Representative__c ORDER BY Active_Leads__c ASC];
            
            //creating unique key identifier for Sales rep to match criteria based on lead records
            for(Sales_Representative__c objSalesRep : list_SalesRep) {
                map_keyValuesBySalesRep.put(objSalesRep.Location__c+'-'+objSalesRep.Industry_Specialization__c+'-'+objSalesRep.Source_Specialization__c,
                                            objSalesRep);
            }
            
            Map<String,Lead> map_keyvaluesByLeadRecord = new Map<String,Lead>();
            Sales_Representative__c objSalesRepresentative = new Sales_Representative__c();
            List<Sales_Representative__c> list_updateSalesRepWorkCount = new List<Sales_Representative__c>();
            List<Lead> list_updateLeads = new List<Lead>();
            for(Lead objLead : list_newLeads) {
                map_keyvaluesByLeadRecord.put(objLead.Location__c+'-'+objLead.Industry+'-'+objLead.LeadSource,
                                              objLead);
                objSalesRepresentative = new Sales_Representative__c();
                //match and retrieve the key pair from the sales rep map
                objSalesRepresentative = map_keyValuesBySalesRep.get(objLead.Location__c+'-'+objLead.Industry+'-'+objLead.LeadSource);
                objSalesRepresentative.Active_Leads__c = objSalesRepresentative.Active_Leads__c + 1;
                objLead.Sales_Representative__c = objSalesRepresentative.ID;
                list_updateSalesRepWorkCount.add(objSalesRepresentative);
                list_updateLeads.add(objLead);
            }
            UPDATE list_updateSalesRepWorkCount;
        }
        catch(Exception ex) {
            //here we can log error messages
        }
    }
    
    public static void validateLeadToOpportunityCreation(List<Lead> list_newLeads) {
        
        try {
            for(Lead objLead : list_newLeads) {
                
                //Check if the lead is ready to be converted into an Opportunity
                if(objLead.Convert_to_Opportunity__c) {
                    
                    //Since Email and Phone field types are already validated through force.com
                    if(objLead.Email == NULL)
                        objLead.Email.addError('Email cannot be blank');
                    if(objLead.MobilePhone == NULL)
                        objLead.MobilePhone.addError('Mobile Number cannot be blank');
                    if(objLead.Industry == NULL)
                        objLead.Industry.addError('Industry cannot be blank');
                }
            }
        }
        catch(Exception ex) {
            //here we can log error messages
        }
    }
}